### ISSUE TITLE
export 'Transport' (imported as 'Transport') was not found in 'tone' (module has no exports)

### ISSUE THREAD

**Issue by PooLP** [Tonejs/Tone.js#1001]
Hi,
I have the same problem of this issue (https://github.com/Tonejs/Tone.js/issues/674) after update from 14.7.77 to next (14.8.35), i have import error. 
I don't understand, it's work on 14.7.77 without error.

it's a POC in REACT/Typescipt

If you have any idea for this problem i take it :D

**script :**

```ts
import { Analyser, loaded, Meter, Player, Players, Transport } from 'tone';

Transport.bpm.value = 90;
Transport.timeSignature = [4, 4];

Transport.on('loop', (t) => console.log('loop ***', t, Transport.seconds));
Transport.on('start', (t) => console.log('start ***', t, Transport.seconds));
Transport.on('stop', (t) => console.log('stop ***', t, Transport.seconds));

let drumsMeter: Meter;
let drumsAnalyser: Analyser;
let BassMeter: Meter;
let BassAnalyser: Analyser;
let SynthMeter: Meter;
let SynthAnalyser: Analyser;
let KeysMeter: Meter;
let KeysAnalyser: Analyser;
let ModularMeter: Meter;
let ModularAnalyser: Analyser;

let audioplayer: Players;
let drums: Player;
let keys: Player;
let bass: Player;

const musicInit = async () => {

    drumsMeter = new Meter();
    drumsAnalyser = new Analyser({ type: 'fft', size: 64 });
    BassMeter = new Meter();
    BassAnalyser = new Analyser({ type: 'fft', size: 64 });
    SynthMeter = new Meter();
    SynthAnalyser = new Analyser({ type: 'fft', size: 64 });
    KeysMeter = new Meter();
    KeysAnalyser = new Analyser({ type: 'fft', size: 64 });
    ModularMeter = new Meter();
    ModularAnalyser = new Analyser({ type: 'fft', size: 64 });

    audioplayer = new Players({
        urls: {
            drums: 'drums.mp3',
            bass: 'bass.mp3',
            synth: 'synth.mp3',
            keys: 'keys.mp3',
            modular: 'modular.mp3'
        },
        baseUrl: '/audio/',
    }).toDestination();

    await loaded();

    console.log(audioplayer);

    drums = audioplayer.player('drums').sync().start();
    keys = audioplayer.player('keys').sync().start();
    bass = audioplayer.player('bass').sync();

    drums.loop = true;
    keys.loop = true;
    bass.loop = true;

    audioplayer.player('drums').connect(drumsMeter).connect(drumsAnalyser);
    audioplayer.player('bass').connect(BassMeter).connect(BassAnalyser);
    audioplayer.player('synth').connect(SynthMeter).connect(SynthAnalyser);
    audioplayer.player('keys').connect(KeysMeter).connect(KeysAnalyser);
    audioplayer.player('modular').connect(ModularMeter).connect(ModularAnalyser);
};
```

**error :**

```
Compiled with problems:X

WARNING in ./src/components/Store.ts 3:0-19

export 'Transport' (imported as 'Transport') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 4:0-23

export 'Transport' (imported as 'Transport') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 5:0-12

export 'Transport' (imported as 'Transport') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 5:55-72

export 'Transport' (imported as 'Transport') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 6:0-12

export 'Transport' (imported as 'Transport') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 6:57-74

export 'Transport' (imported as 'Transport') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 7:0-12

export 'Transport' (imported as 'Transport') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 7:55-72

export 'Transport' (imported as 'Transport') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 23:21-26

export 'Meter' (imported as 'Meter') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 24:24-32

export 'Analyser' (imported as 'Analyser') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 25:20-25

export 'Meter' (imported as 'Meter') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 26:23-31

export 'Analyser' (imported as 'Analyser') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 27:21-26

export 'Meter' (imported as 'Meter') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 28:24-32

export 'Analyser' (imported as 'Analyser') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 29:20-25

export 'Meter' (imported as 'Meter') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 30:23-31

export 'Analyser' (imported as 'Analyser') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 31:23-28

export 'Meter' (imported as 'Meter') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 32:26-34

export 'Analyser' (imported as 'Analyser') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 33:22-29

export 'Players' (imported as 'Players') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 43:10-16

export 'loaded' (imported as 'loaded') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 78:16-31

export 'Transport' (imported as 'Transport') was not found in 'tone' (module has no exports)


WARNING in ./src/components/Store.ts 83:16-30

export 'Transport' (imported as 'Transport') was not found in 'tone' (module has no exports)
```

**Comment by jtwigg** [comment]
+1 
I found myself in this state.

a) When I performed the same upgrade to 14.8.35, I started noticing this error when developing
https://github.com/facebook/create-react-app/issues/11771
```
Uncaught ReferenceError: process is not defined
at Object.4043 (<anonymous>:2:13168)
at r (<anonymous>:2:306599)
at Object.8048 (<anonymous>:2:9496)
at r (<anonymous>:2:306599)
at Object.8641 (<anonymous>:2:1379)
at r (<anonymous>:2:306599)
at <anonymous>:2:315627
at <anonymous>:2:324225
at <anonymous>:2:324229
at HTMLIFrameElement.e.onload (index.js:1)
```

b) The recommendation was to upgrade to `"react-scripts": "^5.0.0",`
which led to the errors listed in this description 
```
export 'Transport' (imported as 'Transport') was not found in 'tone' (module has no exports)
```

I've had a lot of problems with ToneJS loading in NextJS apps, as well as starting playing audio too early before various background callbacks occur. Its something to do with it operating as an ESM module I suspect? 

**Some canonical documentation about setting up ToneJS in a React app would be great.**

**Comment by jtwigg** [comment]
I provided a demo project of this failing.
https://github.com/jtwigg/ToneJSReact

1) This was built using an up to date React app using the below template. It is using `react-script 5.0` 
https://github.com/blackarctic/create-react-app

2) I installed `tone@next` and made a simple `onAction: () => { Tone.start()` function call

now `npm run build` fails with:
```
Attempted import error: 'start' is not exported from 'tone' (imported as 'Tone').
```

**Any suggestions?**

**Comment by jtwigg** [comment]
I'll give another poke on this. I was cornered into upgrading `react-scripts` again and car crashed into this again.

**Comment by shahnizz** [comment]
FWIW I'm also running into similar issues with CRA and the latest version of tone@next

```
import * as Tone from 'tone';
const synth = new Tone.PolySynth().toDestination();
```

`Attempted import error: 'PolySynth' is not exported from 'tone' (imported as 'Tone').`

**Comment by dirkk0** [comment]
> FWIW I'm also running into similar issues with CRA and the latest version of tone@next
> 
> ```
> import * as Tone from 'tone';
> const synth = new Tone.PolySynth().toDestination();
> ```
> 
> `Attempted import error: 'PolySynth' is not exported from 'tone' (imported as 'Tone').`

... and it does work with 14.8.26?

**Comment by shahnizz** [comment]
> > FWIW I'm also running into similar issues with CRA and the latest version of tone@next
> > ```
> > import * as Tone from 'tone';
> > const synth = new Tone.PolySynth().toDestination();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `Attempted import error: 'PolySynth' is not exported from 'tone' (imported as 'Tone').`
> 
> ... and it does work with 14.8.26?

Ah yes so `yarn add tone@14.8.26` has seemed to resolve the issue and the project builds and runs properly at that release.

**Comment by tambien** [comment]
sounds like it's fixed with the latest version? i'll close this then and plan on promoting tone@next to tone@latest soon

**Comment by paulmelnikow** [comment]
Hey @tambien, I think this problem persists, at least in the latest published version 14.8.38.

With a brand new `create-react-app --template typescript` (`react-scripts@5.0.0`), I get this message:

```
export 'start' (imported as 'Tone') was not found in 'tone' (module has no exports)
```

I'm working around it using 14.8.26. Would be happy to help work on this if it's helpful!

**Comment by peilingjiang** [comment]
I've tried 14.7.77, 14.8.38, and 14.8.26 and none of them works for me.

**Comment by slocka** [comment]
@tambien I think it would be good to re-open this issue as I believe it has never been fixed. I tried different versions and it seems that `14.8.29` is the last version that is working but it is 9 months old so we are stuck with that version and can't get all the bug fixes that were merged since then. 

All the packages `>=14.8.30` are breaking the build as described in the posts above, so it seems that one of the change between `14.8.29` and `14.8.30` broke it but I don't have visibility on what are those changes.

**Comment by jdelStrother** [comment]
I ended up added this to my webpack config - 

```js
{
  module: {
    rules: [
      {
        test: /node_modules\/tone/,
        resolve: {
          fullySpecified: false,
        },
      },
    ],
  },
}
```

which seems to have worked ok for, eg, 

```ts
import * as TonePlayer from "tone/build/esm/source/buffer/Player";
```

(It still doesn't work on a simple `import * as Tone from "tone"`, which produces `export 'Player' (imported as 'Tone') was not found in 'tone' (module has no exports)`.)
