### ISSUE TITLE
Firefox 61 beta breaks some effects

### ISSUE THREAD

**Issue by 17cupsofcoffee** [Tonejs/Tone.js#340]
I'm using the beta channel of Firefox as my main browser at the minute, and I noticed that since I upgraded to version 61 (which came out in the last few days, I think?), a bunch of Tone.js effects no longer seem to work (`Freeverb`, `JCReverb`, `PingPongDelay`, etc.).

Here's a reproduction of the issue in JSFiddle - it's just the code example from the `Freeverb` docs page: https://jsfiddle.net/em6c13nr/

Not a huge issue for me, as I can use other browsers to test my code in the meantime, but I thought I should point it out before Firefox 61 makes its way to stable :)

**Comment by tambien** [comment]
Good to know. will investigate! lmk if you find the exact spot where that's being thrown from.

**Comment by tambien** [comment]
Looks like simply commenting out these [two lines fixes it](https://github.com/Tonejs/Tone.js/blob/e6faa39dbae91fbabaae87b47c6f4bfcd5c87c95/Tone/component/Split.js#L24-L25). I guess [the spec](https://webaudio.github.io/web-audio-api/#audionode-channelcountmode-constraints) has been updated so that channelCount and channelCountMode are both already defined in this manner and throw an error when set. 

i will try committing that change.

**Comment by 17cupsofcoffee** [comment]
Aha, I fixed my project's dodgy sourcemaps and that is indeed where the error is coming from 😄 

Thank you for the quick response!

**Comment by 17cupsofcoffee** [comment]
Brilliant, thank you so much!

**Comment by joegaffey** [comment]
Hi. I'm still seeing this issue in the latest release. A patched version with the two lines commented out works fine though.

**Comment by tambien** [comment]
@joegaffey are you using a version which is greater than tone@13.1.6? So far this fix hasn't made its way into a release it's still on the `dev` branch.

**Comment by joegaffey** [comment]
Sorry no, I thought that the fix was in the 13.1.6 release based on a previous [comment](https://github.com/Tonejs/Tone.js/issues/340#issuecomment-386440641). 
Thanks for the clarification and great work on the library!

**Comment by donkeypagoda** [comment]
This just saved me, was having total destruction in firefox, the 13.1.6 works great.  Thanks for the support and the awesome library @tambien
