### ISSUE TITLE
Tone.Player: When playbackRate < 1, the duration of the audio playback is proportionally shorter

### ISSUE THREAD

**Issue by Sterv** [Tonejs/Tone.js#375]
When the playbackRate of a Player is set to a number less than 1, the audio sample does not play to completion - it is proportionally shorter. In other words, If the playbackRate is .5, .5 of the audio sample will not be played. 

I created a demo to demonstrate this and it is hosted at https://www.sterv.com/tonejs/bug1. In this demo, I used a simple React component that takes an audio file's url and playback rate as props (https://gist.github.com/Sterv/3a245dbe316cbb2cedb85a84d4d1b979).

This issue is a continuation of: https://github.com/Tonejs/Tone.js/issues/292

**Comment by tambien** [comment]
looks like you're using r12. this should be fixed on the latest dev release. `npm install tone@next`

**Comment by Sterv** [comment]
I updated to tone@next and its still not working: https://www.sterv.com/tonejs/bug1

**Comment by timothyboie** [comment]
[https://github.com/Tonejs/Tone.js/blob/dev/Tone/source/BufferSource.js#L222]

Math.min will use the second parameter of buffer.duration instead of computedDur, since buffer.duration will be a lower value when playbackRate < 1.

Need to test a bit before submitting fix.  This should be a good start though.

**Comment by Sterv** [comment]
@tboie any luck with your approach?

**Comment by Sterv** [comment]
That solved it for me. Thanks so much @tboie. 

https://www.sterv.com/tonejs/bug1

@tambien - do you see any issues with his note above?

**Comment by jhrtn** [comment]
I encountering the same problem with a DJ webapp I'm building. Thanks for the patch @tboie - though I was initially experiencing the same problem with patch-3 I built from patch-2 and was able to get the desired behaviour
