### ISSUE TITLE
Feature request: a better way to resume audio context when "interrupted"

### ISSUE THREAD

**Issue by bryanbraun** [Tonejs/Tone.js#767]
Currently, `Context.resume()` is great at resuming the audio context when the state is `suspended` (for example, when [the browser's autoplay policy](https://github.com/Tonejs/Tone.js/wiki/Autoplay) prevents audio on initial page load).

However, the audio context can also be put into a state of `interrupted`. I just learned that Safari and mobile Safari does this when there's an incoming call, browser dialog, or headphone jack removal (and possibly other situations). It appears this state is non-standard since [I don't see it in the spec](https://webaudio.github.io/web-audio-api/#BaseAudioContext).

When the state is `interrupted`, Tone's `Tone.context.resume()` does NOT resume the context (see [the code here](https://github.com/Tonejs/Tone.js/blob/aed85b0f47467b03209a0f0c435af01b1dc6f027/Tone/core/context/Context.ts#L441), which only checks for a `suspended` state). I expected this to resume the context, because the browser's `AudioContext.resume()` DOES resume the context (see [the examples in these webkit tests](https://github.com/WebKit/webkit/blob/master/LayoutTests/webaudio/audiocontext-state-interrupted.html)).

**My workaround:** find the AudioContext inside the ToneJS wrapper and run the `Tone.context._context.resume()` function. I'm not sure if it's a good idea for me to call an underscore method directly...

**Example (which includes steps to reproduce):** https://jsfiddle.net/bryanbraun/ou23xakm/18

<hr>

<small>Note: the workaround works, so I don't think this is urgent. It's just confusing to debug because I thought that Tone's `Context.resume()` was the same as the browser's `AudioContext.resume()`. Some documentation could improve this, but I think the long-term fix is making Tone's `Context.resume()` resume other states besides just `suspended`.</small>

<small>Thanks for the amazing library! It's been incredibly helpful in building out https://musicboxfun.com.</small>

**Comment by bryanbraun** [comment]
I put together [a PR](https://github.com/Tonejs/Tone.js/pull/768), since my head was already in this space and it seemed straightforward. Let me know what you think!

**Comment by chrisguttandin** [comment]
Hi @bryanbraun, I thought this was fixed already as mentioned here #716.

I'm not sure if @tambien published that already, though. Could you maybe try using tone@next?

**Comment by bryanbraun** [comment]
Oh! I'm not sure how I missed that PR. 🤦 

I just tried `tone@next` but I'm still seeing the issue. Here's my jsFiddle example, updated to use `tone@next`: https://jsfiddle.net/bryanbraun/ou23xakm/20/

 I see that [something was updated in standardized-audio-context](https://github.com/Tonejs/Tone.js/pull/716#issuecomment-688272782), which is now available in `tone@next`. I'm having a hard time following how that change impacts Tone.js in a way that would fix this issue.

I understand the concerns in the original PR about putting logic for non-standard browsers in Tone.js. For what it's worth, [the PR I submitted](https://github.com/Tonejs/Tone.js/pull/768) takes a different approach that doesn't add any logic for non-standard browsers. Maybe the maintainers would be more open to merging that one?

**Comment by chrisguttandin** [comment]
Hi @bryanbraun,

thanks for providing that fiddle. So far I did not know that there are multiple types of the interrupted state. The one that is handled in standardized-audio-context is the one that occurs when the user switches to a different tab. I thought that covers all occasions of the interrupted state.

My gut feeling is not to add a special workaround just for the confirm dialog to standardized-audio-context since using the confirm dialog is considered a bad practice. However if the confirm dialog behaves the same as an incoming call, I think that warrants adding a fix.

Do you have a callable iOS device? If so could you please double check that incoming calls behave like the confirm dialog and not like a tab switch?

**Comment by bryanbraun** [comment]
Sorry, we're all Android at my house. ¯\_(ツ)_/¯

I haven't seen the incoming call situation myself. I found these open issues on other projects mentioning it:

- [Mobile Safari sound muted after incoming call](https://github.com/CreateJS/SoundJS/issues/264)
- [Phaser does not handle WebAudio interrupted state](https://gitmemory.com/issue/photonstorm/phaser-ce/667/629604384)

***

I don't think a special workaround is necessary. The native audiocontext `resume()` works fine in all browsers. [The spec for `resume`](https://www.w3.org/TR/webaudio/#dom-audiocontext-resume) says this:

> If the state attribute of the AudioContext is not already "running": Set the state attribute of the AudioContext to "running".

That's perfect! It handles "suspended," "interrupted", or whatever non-standard states get added or removed. That's why [my PR](https://github.com/Tonejs/Tone.js/pull/768/files) just defers to the native API.:

```diff
resume(): Promise<void> {
- 	if (this._context.state === "suspended" && isAudioContext(this._context)) {
+ 	if (isAudioContext(this._context)) {
		return this._context.resume();
	}
```

If we don't want to change Tone's `resume()`, that's cool, since I'm not blocked from using the native AudioContext. 👍

**Comment by chrisguttandin** [comment]
Thanks Bryan. Just to avoid any misunderstandings, I'm not the maintainer or author of Tone. Tone is the great work of @tambien. It's up to him if your changes land in Tone.

But Tone uses standardized-audio-context under the hood and that's the library that I maintain. And with that I'm trying to be very pedantic with the spec. I want it to be as spec compliant as possible. The problem is that there is no `'interrupted'` state in the spec. And if the developer starts an `OscillatorNode` on a `'running'` context they should be sure that it will keep on running indefinitely unless they stop it. That's why I want to prevent the `'interrupted'` state whenever possible since it breaks that guarantee.

Speaking of spec compatibility ... maybe the `'interrupted'` state is coming to the spec at some point. https://github.com/WebAudio/web-audio-api/issues/72#issuecomment-24424663

I don't really know what would be best to do with this problem now.
